services:
  - type: web
    name: tradeai-companion
    runtime: python3
    buildpack: python
    pythonVersion: "3.13.4"
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m aiohttp.web -H 0.0.0.0 -P $PORT main:app"
    envVars:
      - key: TELEGRAM_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_API_SECRET
        sync: false
      - key: ALPACA_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: CHART_IMG_API_KEY
        sync: false
      # Note: The above environment variables with sync: false must be set manually
      # in the Render dashboard under Environment Variables section
      - key: DATABASE_URL
        fromDatabase:
          name: tradeai-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: REDIS_URL
        fromService:
          type: redis
          name: tradeai-redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: .
      - key: TZ
        value: UTC
      - key: PYTHONUNBUFFERED
        value: 1

  - type: redis
    name: tradeai-redis
    plan: starter
    ipAllowList: []

databases:
  - name: tradeai-db
    plan: starter
    databaseName: tradeai_companion
    user: tradeai_user
